### PR TITLE
fix: only prerender for static target

### LINKED ISSUE #76: fix: route is prerendered even for ssr build
Currently a built nuxt page using this module has its `robots.txt` prerendered. That means that e.g. a `Sitemap: (req) => ...req.headers.host...` function has its host set to `localhost` at build time and does not allow dynamic content at deployment.

In PR #75 I changed that behavior to only prerender the route for `target: static`. I added tests to ensure no unwanted regressions.

### PR DESCRIPTION
**Pull request by dargmuesli**
Currently, the `/robots.txt` route is prerendered even for server deployments. A demo for that behavior can be observed in the first commit of this PR which adds a test that currently fails.

Closes #76.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -47,9 +47,11 @@ export default defineNuxtModule<ModuleOptions>({
       getContents: () => `export default ${JSON.stringify(options.rules, null, 2)}`
     }).dst || '')
 
-    nuxt.hook('nitro:build:before', (nitro) => {
-      nitro.options.prerender.routes.push(`/${ROBOTS_FILENAME}`)
-    })
+    if (nuxt.options.target === 'static') {
```
Comment (ricardogobbosouza) [inline src/module.ts:50]: Use `if (nuxt.options._generate) {` instead of `if (nuxt.options.target === 'static') {`

The user does not always define the target

**Review by ricardogobbosouza — CHANGES_REQUESTED** [review]

File: src/module.ts (hunk 1 above)
Comment (ricardogobbosouza) [reply src/module.ts]: I updated the test if you don't mind 😄

Comment (dargmuesli) [reply src/module.ts]: Ahh, `nuxtConfig` it is! Thank you :heart: it's kind of hard to find documentation for the edge test utils, right? Or have I just looked at wrong places?

Comment (ricardogobbosouza) [reply src/module.ts]: The documentation is very simple https://v3.nuxtjs.org/getting-started/testing

I know the options because I helped to develop 😅
